### PR TITLE
WIP: Make sure the browser does not show the access-key in the logs

### PR DESCRIPTION
**Pull request by NicolasDorier**
Attempt to fix https://github.com/ShahanaFarooqui/RTL/issues/58

### CODE REVIEW

**Comment by NicolasDorier** [comment]
NAAAAH wait I was testing it

**Comment by ShahanaFarooqui** [comment]
yup, because i pull and tested it on my local and that failed :(

**Comment by NicolasDorier** [comment]
btw, funny story: Actually in .8, if you give you `access_key` to a page which does not exist, it get properly processed and nothing appear in the browser!!

**Comment by ShahanaFarooqui** [comment]
i was just confused if i should publish a release or not? :)

**Comment by NicolasDorier** [comment]
I am testing, revert it :p

**Comment by ShahanaFarooqui** [comment]
sure

**Comment by NicolasDorier** [comment]
This is fun, actually even in .8, I can log in without trace. I just need to post to:
https://example.com/rtl/LOLOLOL?access_key=mykey

**Comment by NicolasDorier** [comment]
The bug has unexpectedly the expected behavior.

**Comment by ShahanaFarooqui** [comment]
For non-existent routes, node server will simply assume that the route exists within Angular. So for all non existent API request, we serve pre build angular with index.html. But, the access_key has to be correct :P

**Comment by NicolasDorier** [comment]
reopened https://github.com/ShahanaFarooqui/RTL/pull/61

**Pull request merged**
